io:
  logdir: logs/
  datadir: /data/roofmapset/
  resume_from: 
  num_workers: 8
  tensorboard_port: 0
  # validation_interval: 24000  # Commented out - validate after every epoch instead

model:
  image:
      mean: [109.730, 103.832, 98.681]
      stddev: [22.275, 22.124, 23.229]

  batch_size: 8
  batch_size_eval: 1

  # backbone multi-task parameters
  head_size: [[2], [1], [2]]

  # backbone parameters
  backbone: stacked_hourglass
  depth: 4
  num_stacks: 2
  num_blocks: 1

  # sampler parameters
  ## static sampler
  n_stc_posl: 300
  n_stc_negl: 40

  ## dynamic sampler
  n_dyn_junc: 300
  n_dyn_posl: 300
  n_dyn_negl: 80
  n_dyn_othr: 600

  # LOIPool layer parameters
  n_pts0: 64
  n_pts1: 8

  # line verification network parameters
  dim_loi: 128
  dim_fc: 1024

  # maximum junction and line outputs
  n_out_junc: 250
  n_out_line: 2500

  # additional ablation study parameters
  use_cood: 0
  use_slop: 0
  use_conv: 0

  # junction threashold for evaluation (See #5)
  eval_junc_thres: 0.008

optim:
  name: Adam
  lr: 0.001
  amsgrad: True
  weight_decay: 0
  max_epoch: 30
  lr_decay_epoch: 10
